import type { GuideImage, GuideSource } from '../types'

export const sourceRegistry: GuideSource[] = [
  {
    title: 'No Rest for the Wicked 官网',
    url: 'https://www.norestforthewicked.com/',
    type: 'official',
    language: 'en',
  },
  {
    title: 'Steam 商店页面',
    url: 'https://store.steampowered.com/app/1371980/No_Rest_for_the_Wicked/',
    type: 'official',
    language: 'en',
  },
  {
    title: 'Fextralife Wiki 总览',
    url: 'https://norestforthewicked.wiki.fextralife.com/No%2BRest%2BFor%2BThe%2BWicked%2BWiki',
    type: 'wiki',
    language: 'en',
  },
  {
    title: 'Fextralife Weapons',
    url: 'https://norestforthewicked.wiki.fextralife.com/Weapons',
    type: 'wiki',
    language: 'en',
  },
  {
    title: 'Fextralife Bosses',
    url: 'https://norestforthewicked.wiki.fextralife.com/Bosses',
    type: 'wiki',
    language: 'en',
  },
  {
    title: 'Fextralife Warrick the Torn',
    url: 'https://norestforthewicked.wiki.fextralife.com/Warrick+the+Torn',
    type: 'wiki',
    language: 'en',
  },
  {
    title: 'Fextralife The Riven Twins',
    url: 'https://norestforthewicked.wiki.fextralife.com/The+Riven+Twins',
    type: 'wiki',
    language: 'en',
  },
  {
    title: 'Fextralife Falstead Darak',
    url: 'https://norestforthewicked.wiki.fextralife.com/Falstead+Darak',
    type: 'wiki',
    language: 'en',
  },
  {
    title: 'Fextralife Echo Knight',
    url: 'https://norestforthewicked.wiki.fextralife.com/Echo+Knight',
    type: 'wiki',
    language: 'en',
  },
  {
    title: 'Fextralife Guides & Walkthroughs',
    url: 'https://norestforthewicked.wiki.fextralife.com/Guides%2B%26%2BWalkthroughs',
    type: 'guide',
    language: 'en',
  },
  {
    title: 'wiki.gg Equipment',
    url: 'https://nrftw.wiki.gg/wiki/Equipment',
    type: 'wiki',
    language: 'en',
  },
  {
    title: 'Moon Studios The Breach 官方展示',
    url: 'https://www.youtube.com/watch?v=CzAtYaSYZms',
    type: 'official',
    language: 'en',
  },
  {
    title: 'The Breach 官方预告',
    url: 'https://www.youtube.com/watch?v=mpoMEYnvA5Q',
    type: 'official',
    language: 'en',
  },
  {
    title: 'Steam 社区截图',
    url: 'https://steamcommunity.com/app/1371980/screenshots/',
    type: 'community',
    language: 'en',
  },
  {
    title: 'Fextralife The Lost Huntress',
    url: 'https://norestforthewicked.wiki.fextralife.com/The+Lost+Huntress',
    type: 'wiki',
    language: 'en',
  },
  {
    title: 'Fextralife The Caretaker and the Tusk',
    url: 'https://norestforthewicked.wiki.fextralife.com/The+Caretaker+and+the+Tusk',
    type: 'wiki',
    language: 'en',
  },
  {
    title: 'Fextralife The Winged Brood',
    url: 'https://norestforthewicked.wiki.fextralife.com/The+Winged+Brood',
    type: 'wiki',
    language: 'en',
  },
  {
    title: 'Fextralife The Unbreakable Egg',
    url: 'https://norestforthewicked.wiki.fextralife.com/The+Unbreakable+Egg',
    type: 'wiki',
    language: 'en',
  },
  {
    title: 'Fextralife New Player Help',
    url: 'https://norestforthewicked.wiki.fextralife.com/New+Player+Help',
    type: 'guide',
    language: 'en',
  },
  {
    title: 'Fextralife Walkthrough',
    url: 'https://norestforthewicked.wiki.fextralife.com/Walkthrough',
    type: 'guide',
    language: 'en',
  },
  {
    title: 'Fextralife Side Quests',
    url: 'https://norestforthewicked.wiki.fextralife.com/Side+Quests',
    type: 'guide',
    language: 'en',
  },
  {
    title: 'Fextralife Endings',
    url: 'https://norestforthewicked.wiki.fextralife.com/Endings',
    type: 'guide',
    language: 'en',
  },
  {
    title: 'Fextralife Crafting',
    url: 'https://norestforthewicked.wiki.fextralife.com/Crafting',
    type: 'guide',
    language: 'en',
  },
  {
    title: 'Fextralife New Game Plus',
    url: 'https://norestforthewicked.wiki.fextralife.com/New+Game+%2B',
    type: 'guide',
    language: 'en',
  },
  {
    title: 'Fextralife Trophy & Achievement Guide',
    url: 'https://norestforthewicked.wiki.fextralife.com/Trophy+%26+Achievement+Guide',
    type: 'guide',
    language: 'en',
  },
  {
    title: 'Fextralife Housing',
    url: 'https://norestforthewicked.wiki.fextralife.com/Housing',
    type: 'guide',
    language: 'en',
  },
]

export const sourceShortcuts: Record<string, GuideSource> = {
  official: sourceRegistry[0],
  steam: sourceRegistry[1],
  fextralife: sourceRegistry[2],
  'fextralife-weapons': sourceRegistry[3],
  'fextralife-bosses': sourceRegistry[4],
  'boss-warrick': sourceRegistry[5],
  'boss-riven-twins': sourceRegistry[6],
  'boss-falstead-darak': sourceRegistry[7],
  'boss-echo-knight': sourceRegistry[8],
  'fextralife-guides': sourceRegistry[9],
  'wikigg-equipment': sourceRegistry[10],
  'breach-showcase': sourceRegistry[11],
  'breach-trailer': sourceRegistry[12],
  'steam-community': sourceRegistry[13],
  'boss-lost-huntress': sourceRegistry[14],
  'boss-caretaker-tusk': sourceRegistry[15],
  'boss-winged-brood': sourceRegistry[16],
  'boss-unbreakable-egg': sourceRegistry[17],
  'guide-new-player-help': sourceRegistry[18],
  'guide-walkthrough': sourceRegistry[19],
  'guide-side-quests': sourceRegistry[20],
  'guide-endings': sourceRegistry[21],
  'guide-crafting': sourceRegistry[22],
  'guide-new-game-plus': sourceRegistry[23],
  'guide-achievements': sourceRegistry[24],
  'guide-housing': sourceRegistry[25],
}

export const officialImages: GuideImage[] = [
  {
    url: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1371980/331de7e745f43867f0a220339153ac6019822ea4/header.jpg?t=1780442295',
    alt: 'No Rest for the Wicked Steam header',
    caption: '官方 Steam 商店头图',
    sourceUrl: 'https://store.steampowered.com/app/1371980/No_Rest_for_the_Wicked/',
    licenseNote: 'Steam 商店公开媒体素材，保留来源链接。',
  },
  {
    url: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1371980/079327abaf4866604f9f77200ded37da18d7089e/ss_079327abaf4866604f9f77200ded37da18d7089e.1920x1080.jpg?t=1780442295',
    alt: 'No Rest for the Wicked combat screenshot',
    caption: '战斗场景参考图',
    sourceUrl: 'https://store.steampowered.com/app/1371980/No_Rest_for_the_Wicked/',
    licenseNote: 'Steam 商店公开截图，保留来源链接。',
  },
  {
    url: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1371980/56066f44f29e8b042c482e0b0680bc101bf1ecd5/ss_56066f44f29e8b042c482e0b0680bc101bf1ecd5.1920x1080.jpg?t=1780442295',
    alt: 'No Rest for the Wicked exploration screenshot',
    caption: '区域探索参考图',
    sourceUrl: 'https://store.steampowered.com/app/1371980/No_Rest_for_the_Wicked/',
    licenseNote: 'Steam 商店公开截图，保留来源链接。',
  },
  {
    url: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1371980/1163c9191d2261d845aa96cbc011ed6490182ae8/ss_1163c9191d2261d845aa96cbc011ed6490182ae8.1920x1080.jpg?t=1780442295',
    alt: 'No Rest for the Wicked town screenshot',
    caption: '圣城与城镇功能参考图',
    sourceUrl: 'https://store.steampowered.com/app/1371980/No_Rest_for_the_Wicked/',
    licenseNote: 'Steam 商店公开截图，保留来源链接。',
  },
  {
    url: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1371980/ss_01a87d9ec6cef10244eb5dd8d3f55047060da954.1920x1080.jpg?t=1780442295',
    alt: 'No Rest for the Wicked boss arena screenshot',
    caption: 'Boss 战场景参考图',
    sourceUrl: 'https://store.steampowered.com/app/1371980/No_Rest_for_the_Wicked/',
    licenseNote: 'Steam 商店公开截图，保留来源链接。',
  },
]

export const imageShortcuts: Record<string, GuideImage> = {
  'steam-hero': officialImages[0],
  'steam-combat': officialImages[1],
  'steam-explore': officialImages[2],
  'steam-town': officialImages[3],
  'steam-boss': officialImages[4],
  'boss-warrick': {
    url: 'https://norestforthewicked.wiki.fextralife.com/file/No-Rest-For-The-Wicked/warrick-the-torn-boss-no-rest-for-the-wicked-wiki-guide.jpg',
    alt: 'Warrick the Torn boss image',
    caption: 'Warrick the Torn Boss 图鉴',
    sourceUrl: 'https://norestforthewicked.wiki.fextralife.com/Warrick+the+Torn',
    licenseNote: 'Fextralife Wiki 图片，保留原图与来源链接，不移除水印或标识。',
  },
  'boss-riven-twins': {
    url: 'https://norestforthewicked.wiki.fextralife.com/file/No-Rest-For-The-Wicked/the-riven-twins-boss-no-rest-for-the-wicked-wiki-guide.jpg',
    alt: 'The Riven Twins boss image',
    caption: 'The Riven Twins Boss 图鉴',
    sourceUrl: 'https://norestforthewicked.wiki.fextralife.com/The+Riven+Twins',
    licenseNote: 'Fextralife Wiki 图片，保留原图与来源链接，不移除水印或标识。',
  },
  'boss-falstead-darak': {
    url: 'https://norestforthewicked.wiki.fextralife.com/file/No-Rest-For-The-Wicked/falstead-derek-boss-no-rest-for-the-wicked-wiki-guide.jpg',
    alt: 'Falstead Darak boss image',
    caption: 'Falstead Darak Boss 图鉴',
    sourceUrl: 'https://norestforthewicked.wiki.fextralife.com/Falstead+Darak',
    licenseNote: 'Fextralife Wiki 图片，保留原图与来源链接，不移除水印或标识。',
  },
  'boss-echo-knight': {
    url: 'https://norestforthewicked.wiki.fextralife.com/file/No-Rest-For-The-Wicked/echo-knight-boss-no-rest-for-the-wicked-wiki-guide.jpg',
    alt: 'Echo Knight boss image',
    caption: 'Echo Knight Boss 图鉴',
    sourceUrl: 'https://norestforthewicked.wiki.fextralife.com/Echo+Knight',
    licenseNote: 'Fextralife Wiki 图片，保留原图与来源链接，不移除水印或标识。',
  },
  'boss-lost-huntress': {
    url: 'https://norestforthewicked.wiki.fextralife.com/file/No-Rest-For-The-Wicked/the-lost-huntress-boss-nrftw-wiki-guide-300px.jpg',
    alt: 'The Lost Huntress boss image',
    caption: 'The Lost Huntress Boss 图鉴',
    sourceUrl: 'https://norestforthewicked.wiki.fextralife.com/The+Lost+Huntress',
    licenseNote: 'Fextralife Wiki 图片，保留原图与来源链接，不移除水印或标识。',
  },
  'boss-caretaker-tusk': {
    url: 'https://norestforthewicked.wiki.fextralife.com/file/No-Rest-For-The-Wicked/the-caretaker-the-tusk-boss-nrftw-wiki-guide-300px.jpg',
    alt: 'The Caretaker and the Tusk boss image',
    caption: 'The Caretaker and the Tusk Boss 图鉴',
    sourceUrl: 'https://norestforthewicked.wiki.fextralife.com/The+Caretaker+and+the+Tusk',
    licenseNote: 'Fextralife Wiki 图片，保留原图与来源链接，不移除水印或标识。',
  },
  'boss-winged-brood': {
    url: 'https://norestforthewicked.wiki.fextralife.com/file/No-Rest-For-The-Wicked/the-winged-brood-boss-nrftw-wiki-guide-300px.png',
    alt: 'The Winged Brood boss image',
    caption: 'The Winged Brood Boss 图鉴',
    sourceUrl: 'https://norestforthewicked.wiki.fextralife.com/The+Winged+Brood',
    licenseNote: 'Fextralife Wiki 图片，保留原图与来源链接，不移除水印或标识。',
  },
  'wiki-crafting-materials': {
    url: 'https://norestforthewicked.wiki.fextralife.com/file/No-Rest-For-The-Wicked/materials-crafting-norestforthewicked-wiki-guide-400px.jpg',
    alt: 'No Rest for the Wicked crafting materials',
    caption: 'Crafting 页面材料图',
    sourceUrl: 'https://norestforthewicked.wiki.fextralife.com/Crafting',
    licenseNote: 'Fextralife Wiki 图片，保留原图与来源链接，不移除水印或标识。',
  },
  'wiki-housing': {
    url: 'https://norestforthewicked.wiki.fextralife.com/file/No-Rest-For-The-Wicked/buy-housing-no-rest-for-the-wicked-wiki-guide.jpg',
    alt: 'No Rest for the Wicked housing guide image',
    caption: 'Housing 页面房屋图',
    sourceUrl: 'https://norestforthewicked.wiki.fextralife.com/Housing',
    licenseNote: 'Fextralife Wiki 图片，保留原图与来源链接，不移除水印或标识。',
  },
  'wiki-side-quest-armor': {
    url: 'https://norestforthewicked.wiki.fextralife.com/file/No-Rest-For-The-Wicked/the-innkeepers-husband-side-quest-no-rest-for-the-wicked-wiki-guide.jpg',
    alt: 'No Rest for the Wicked side quest image',
    caption: 'Fextralife 支线/装备相关页面图片',
    sourceUrl: 'https://norestforthewicked.wiki.fextralife.com/Armor',
    licenseNote: 'Fextralife Wiki 图片，保留原图与来源链接，不移除水印或标识。',
  },
}
